### ISSUE TITLE
Initialize one band with the same value

### ISSUE THREAD

**Issue by ChroMaE3** [airware/buzzard#31]
It is not really an issue, but I'm wondering if there's an easy way to initialize one band with one value. 

Considering a really large raster with n bands. Each of these bands are initialized to 0. If I want to initialize the last band (and only that one) with the value 1:
- can I do that when using `create_raster` ?
- Or is there a way without tiling ?
- Or do I need to fill a numpy array tile to 1 and use the `set_data` function ?

Thanks,
D.

**Comment by Ngoguey42** [comment]
Use the `fill` method of raster
```py
import buzzard as buzz
ds = buzz.DataSouce()
r = ds.create_araster(...)
r.fill(1, len(r)) # Set the last band to 1
```

**Comment by ChroMaE3** [comment]
Perfect :+1:
