### ISSUE TITLE
Topological exceptions

### ISSUE THREAD

**Issue by ChroMaE3** [airware/buzzard#34]
Hey.

When a polygon is not well defined (in particular for self.intersection), a TopologyException is raised. For instance:
```
TopologyException: Input geom 1 is invalid: Self-intersection at or near point xxxxxxxx yyyyyyyy at xxxxxxxx yyyyyyyy
```
It is easily caught, but is there a way using buzzard to try to fix the geometry? And still raise if failed?

**Comment by cfouquetairware** [comment]
i'm not sure it should be in the scope of buzzard to handle fixing shapely errors (especially since fixing a self-intersection it far from trivial if you want to be completely generalistic)

**Comment by ChroMaE3** [comment]
@Ngoguey42 : It happens when computing the intersection of an image and a polygon with a self intersection:
```
common_fp = ds.img.fp.intersection(a_poly)
```
But I think it is a weird raise since even if the polygon is wrong, the fp intersection should be easily computed.

@cfouquetairware : Except if it is handled by an external library already used by Buzzard (for instance Shapely). But the question is more, is it already handled, or not.

**Comment by ChroMaE3** [comment]
(FYI, operations following this intersection are `sub_mask = common_fp.burn_polygons(a_poly)` and then a `set_data`)

**Comment by cfouquetairware** [comment]
Shapely refuses by itself to use intersection with a corrupted polygon, hence the exception you get.
You should ensure that a_poly.is_valid is True before using intersection on it
As per fixing it, you can try to use a_poly = a_poly.buffer(0) before sending it to intersection, it fixes some error cases

**Comment by cfouquetairware** [comment]
Still be careful as these kind of fixes may seriously damage the polygon in some corner cases (bowties)

**Comment by ChroMaE3** [comment]
@cfouquetairware I already caught the exception (`except shapely.errors.TopologicalError`) for a specific treatment.

So I deduce that it is not handled by buzzard, which was my question ;)
