### ISSUE TITLE
Problem with the saving of geojson

### ISSUE THREAD

**Issue by ChroMaE3** [airware/buzzard#35]
Hey. I have an issue while saving some polygons in geojson format. Note that it works perfectly when saving in shapefile format.

The code for saving in shapefile (which is working perfectly, checked on qgis):
```python
generator.ds.create_vector(
        'boat',
        shape_path,
        'polygon',
        fields,
        sr=generator.ds.img.proj4_origin,
        driver='ESRI Shapefile'
    )
```

But when saving in geojson with:
```python
generator.ds.create_vector(
        'boat',
        shape_path,
        'polygon',
        fields,
        sr=generator.ds.img.proj4_origin,
        driver='GeoJSON'
    )
```
this error occurs:
```
ValueError: Missing origin's spatial reference
```

Is there any difference in the creation of geojson compared to shapefile?

**Comment by Ngoguey42** [comment]
From your exemple I deduce that you are using the `mode 2` of the `DataSource`, and since a spatial reference cannot be stored in a `GeoJSON`, this mode raise an error after creation.

A PR that improves the documentation and the variable name on this matter is currently open. Take a look at the improved documentation (I just updated it with you issue).

https://github.com/airware/buzzard/pull/33

**Comment by ChroMaE3** [comment]
Yes, it comes from with mode apparently. No crash with mode 4. Thanks for the update.

I still have a question. Is there some documentation about defining in Buzzard some sr. Let's explain my problem:
- I have some polygons in a projection system (metric one)
- I want to save them in a json (so in WGS84).
I should defined a sr_work in WGS84 I guess. But I don't know how to set it in sr_work (I only used for now `buzz.srs.wkt_of_file`). Is it with `wkt_of_any(string)`? Is there documentation about string format?

**Comment by Ngoguey42** [comment]
`I have some polygons in a projection system (metric one)`

**Comment by Ngoguey42** [comment]
`I have some polygons in a projection system (metric one)`
It means that you are working with this srs (`sr_work`)

`I want to save them in a json (so in WGS84).`
It means that you wan't to create a file with this srs (`sr` parameter in `create_vector` or `sr_forced`)

As written in the `DataSource` documentation the definition of a textual spatial references can be found here http://gdal.org/java/org/gdal/osr/SpatialReference.html#SetFromUserInput-java.lang.String-

**Comment by ChroMaE3** [comment]
I saw this link, but java afraid me haha. Perfect, thank you. Not directly related and I did not investigate on that crash, but with a WGS84 SR, I obtain:

`ValueError: Bad coord transformation for raster proxy: ['tl-tr-br angle is between 89.95751105291073 and 89.95751105312412 degree (should be <90 and >90)']`

I think this error is a little bit weird (in particular parenthesis).

**Comment by ChroMaE3** [comment]
Yes I understood, but this part `'tl-tr-br angle is between 89.95751105291073 and 89.95751105312412 degree (should be <90 and >90)'` is quite funny ;)
