### ISSUE TITLE
gadl install failed

### ISSUE THREAD

**Issue by canghaiyunfan** [airware/buzzard#45]
running install
running bdist_egg
running egg_info
writing GDAL.egg-info/PKG-INFO
writing dependency_links to GDAL.egg-info/dependency_links.txt
writing top-level names to GDAL.egg-info/top_level.txt
reading manifest file 'GDAL.egg-info/SOURCES.txt'
writing manifest file 'GDAL.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/usr/include/python3.5m -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/include -c gdal_python_cxx11_test.cpp -o gdal_python_cxx11_test.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/usr/include/python3.5m -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/include -c gdal_python_cxx11_test.cpp -o gdal_python_cxx11_test.o -std=c++11
building 'osgeo._gdal' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/usr/include/python3.5m -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/include -c extensions/gdal_wrap.cpp -o build/temp.linux-x86_64-3.5/extensions/gdal_wrap.o -std=c++11 -I/usr/include/gdal
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
extensions/gdal_wrap.cpp:4075:1: error: ‘VSIDIR’ does not name a type
 VSIDIR* wrapper_VSIOpenDir( const char * utf8_path,
 ^
extensions/gdal_wrap.cpp:4123:38: error: ‘VSIDIR’ was not declared in this scope
 DirEntry* wrapper_VSIGetNextDirEntry(VSIDIR* dir)
                                      ^
extensions/gdal_wrap.cpp:4123:46: error: ‘dir’ was not declared in this scope
 DirEntry* wrapper_VSIGetNextDirEntry(VSIDIR* dir)
                                              ^
extensions/gdal_wrap.cpp:4124:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
extensions/gdal_wrap.cpp:3225:7: warning: ‘char* get_aligned_buffer(char*, GDALDataType)’ defined but not used [-Wunused-function]
 char* get_aligned_buffer(char* data, GDALDataType ntype)
       ^
extensions/gdal_wrap.cpp:3244:13: warning: ‘void update_buffer_size(void*, char*, char*, size_t)’ defined but not used [-Wunused-function]
 static void update_buffer_size(void* obj, char* data, char* data_aligned, size_t buf_size)
             ^
extensions/gdal_wrap.cpp:3299:5: warning: ‘int GetUseExceptions()’ defined but not used [-Wunused-function]
 int GetUseExceptions() {
     ^
extensions/gdal_wrap.cpp:3305:6: warning: ‘void UseExceptions()’ defined but not used [-Wunused-function]
 void UseExceptions() {
      ^
extensions/gdal_wrap.cpp:3322:6: warning: ‘void DontUseExceptions()’ defined but not used [-Wunused-function]
 void DontUseExceptions() {
      ^
extensions/gdal_wrap.cpp:3370:13: warning: ‘void ClearErrorState()’ defined but not used [-Wunused-function]
 static void ClearErrorState()
             ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

ubuntu :16.04
python: 3.5

**Comment by Ngoguey42** [comment]
Can you add a bit more informations on how you got this error message?

**Comment by canghaiyunfan** [comment]
# Ubuntu: 
sudo add-apt-repository ppa:ubuntugis/ppa 
sudo apt-get update 
sudo apt-get install gdal-bin
sudo apt-get install libgdal-dev 
sudo apt-get install python3-rtree 
export CPLUS_INCLUDE_PATH=/usr/include/gdal export C_INCLUDE_PATH=/usr/include/gdal 
pip install GDAL

I got this error at the last step.

**Comment by Ngoguey42** [comment]
I created an ubuntu Dockerfile to test those commands, and indeed in didn't work!

Follow those instructions:
https://github.com/airware/buzzard/blob/master/doc/ubuntu_install/Dockerfile

Tell me if it works
