### ISSUE TITLE
DXF to Shapely 

### ISSUE THREAD

**Issue by Overdrivr** [airware/buzzard#52]
Hi,

I just discovered this amazing library, and I'm looking for a package capable to load DXF files (that contain straight lines and arcs), load it into a Shapely polygon to be capable to apply geometric transformations on it (rotation, translation).

Is it something that can be achieved with buzzard ? 

Best,

**Comment by Ngoguey42** [comment]
Hi, yes you can achieve that using buzzard.
```py
import buzzard as buzz
list_of_shapely_geometry = list(buzz.open_vector('file.dxf', driver='DXF').iter_data())
```
For the rotations and translations you can then refer to shapely's documentation
